<a href="https://colab.research.google.com/github/kweenkeen/ReachOutandRead/blob/main/Site_Data_Impact_Report.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install xlsxwriter
import pandas as pd
from datetime import date
import zipfile
from google.colab import files
import matplotlib.pyplot as plt

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting xlsxwriter
  Downloading XlsxWriter-3.0.3-py3-none-any.whl (149 kB)
     |████████████████████████████████| 149 kB 8.4 MB/s
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.0.3

In [2]:
progress_report = files.upload()
progress_report = next(iter(progress_report))
progress_df = pd.read_excel(progress_report, converters={'Site ID': str})

Saving MyROR Report 2022-09-16.xlsx to MyROR Report 2022-09-16.xlsx

In [3]:
## UPLOAD SITE DATA REPORT

site_data_report = files.upload()
site_data_report = next(iter(site_data_report))
site_data_df = pd.read_excel(site_data_report, converters={'Site ID': str})

Saving MyROR Site Data Report 2022-09-16.xlsx to MyROR Site Data Report 2022-09-16.xlsx

In [4]:
# CHANGE INDEX TO SITE ID
progress_df = progress_df.set_index('Site ID')
site_data_df = site_data_df.set_index('Site ID')

In [5]:
# APPLY FILTERS

# Filter for high level active sites
high_level_active = ['Active', 'Active - Non-Reporting', 'Slated for deactivation', 'COVID-19 Freeze'] 
progress_df = progress_df[progress_df['Status'].isin(high_level_active)] 
site_data_df = site_data_df[site_data_df['Status'].isin(high_level_active)]

In [6]:
# CREATE LIST OF INSURANCE COLUMN NAMES

insurance_cols = [col for col in progress_df.columns if 'Insurance' in col]
race_ethnicity_cols = [col for col in progress_df.columns if 'Race' in col]
language_cols = [col for col in progress_df.columns if 'Language' in col]

In [7]:
demographic_cols = insurance_cols + race_ethnicity_cols + language_cols

In [8]:
site_data_df.head()

,Site Type,Site Name,Status,Legacy Satellite ID,Affiliate Name,Health System Name,Regions,Categories,Inactivated Reason,Physical Location: Line 1,...,AAB Balance,AAB Date,Scholastic Account,Scholastic Balance,Scholastic Date,Most Recent Quality Classification Date,Most Recent Quality Classification Assessment,Most Recent Quality Classification Activity,"Site is encouraging parents/caregivers to talk, read, sing, and play with their babies at the WCV’s 0-5 months as instructed by the ROR anticipatory guidance",Site wants to give books at all or some WCVs from 0-5 months
Site ID,,,,,,,,,,,,,,,,,,,,,
2,Primary,UAB Primary Care Clinic /,Active,NaN,Reach Out and Read Alabama,NaN,"Prescription for Summer Reading 2018, ACGLR - ...",NaN,NaN,1601 4th Avenue South,...,4455.0,2022-09-15,2660370,2227.5,2022-09-13,2022-08-12,Green,2022-08-12,Y,Y
8,Primary,Quality of Life Health Services /,Active,NaN,Reach Out and Read Alabama,NaN,NaN,NaN,NaN,1411 Piedmont Cut-off,...,0.0,2022-09-15,4577849,0.0,2022-09-13,2018-06-01,Yellow,2018-06-01,Y,Y
24,Primary,Alaska Native Medical Center / PCC-Pediatric C...,Slated for deactivation,NaN,Independent / International,NaN,NaN,"Grant Funded Sites, ROR American Indian/Alaska...",NaN,4320 Diplomacy Drive,...,NaN,NaT,7244523,0.0,2022-09-13,2017-08-02,Yellow,2017-08-02,NaN,NaN
29,Primary,Valleywise Community Health Center- Avondale /,Active,NaN,Reach Out and Read Arizona,NaN,"Southwest Human Development, AZ",NaN,NaN,950 E Van Buren Street,...,NaN,NaT,2693483,0.0,2022-09-13,2021-10-27,Yellow,2021-10-27,Y,Y
30,Primary,Valleywise Community Health Center- Chandler /,Active,NaN,Reach Out and Read Arizona,NaN,"Southwest Human Development, AZ",NaN,NaN,811 S Hamilton,...,NaN,NaT,4613947,0.0,2022-09-13,2021-10-22,Yellow,2021-10-22,Y,Y

In [9]:
site_data_df = site_data_df.reindex(columns = site_data_df.columns.tolist() + demographic_cols)

In [10]:
site_data_df.head()

,Site Type,Site Name,Status,Legacy Satellite ID,Affiliate Name,Health System Name,Regions,Categories,Inactivated Reason,Physical Location: Line 1,...,Language: Somali,Language: Spanish,Language: Swahili,Language: Tagalog,Language: Vietnamese,Language: Unknown / Not Reported,Language: Please Specify,Language: Other 1,Language: Please Specify.1,Language: Other 2
Site ID,,,,,,,,,,,,,,,,,,,,,
2,Primary,UAB Primary Care Clinic /,Active,NaN,Reach Out and Read Alabama,NaN,"Prescription for Summer Reading 2018, ACGLR - ...",NaN,NaN,1601 4th Avenue South,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Primary,Quality of Life Health Services /,Active,NaN,Reach Out and Read Alabama,NaN,NaN,NaN,NaN,1411 Piedmont Cut-off,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Primary,Alaska Native Medical Center / PCC-Pediatric C...,Slated for deactivation,NaN,Independent / International,NaN,NaN,"Grant Funded Sites, ROR American Indian/Alaska...",NaN,4320 Diplomacy Drive,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Primary,Valleywise Community Health Center- Avondale /,Active,NaN,Reach Out and Read Arizona,NaN,"Southwest Human Development, AZ",NaN,NaN,950 E Van Buren Street,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Primary,Valleywise Community Health Center- Chandler /,Active,NaN,Reach Out and Read Arizona,NaN,"Southwest Human Development, AZ",NaN,NaN,811 S Hamilton,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
for i in demographic_cols:
  for j, rows in site_data_df.iterrows():
    site_data_df.loc[j, i] = progress_df.loc[j, i]

In [12]:
site_data_df.head()

,Site Type,Site Name,Status,Legacy Satellite ID,Affiliate Name,Health System Name,Regions,Categories,Inactivated Reason,Physical Location: Line 1,...,Language: Somali,Language: Spanish,Language: Swahili,Language: Tagalog,Language: Vietnamese,Language: Unknown / Not Reported,Language: Please Specify,Language: Other 1,Language: Please Specify.1,Language: Other 2
Site ID,,,,,,,,,,,,,,,,,,,,,
2,Primary,UAB Primary Care Clinic /,Active,NaN,Reach Out and Read Alabama,NaN,"Prescription for Summer Reading 2018, ACGLR - ...",NaN,NaN,1601 4th Avenue South,...,NaN,0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Primary,Quality of Life Health Services /,Active,NaN,Reach Out and Read Alabama,NaN,NaN,NaN,NaN,1411 Piedmont Cut-off,...,NaN,0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Primary,Alaska Native Medical Center / PCC-Pediatric C...,Slated for deactivation,NaN,Independent / International,NaN,NaN,"Grant Funded Sites, ROR American Indian/Alaska...",NaN,4320 Diplomacy Drive,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Primary,Valleywise Community Health Center- Avondale /,Active,NaN,Reach Out and Read Arizona,NaN,"Southwest Human Development, AZ",NaN,NaN,950 E Van Buren Street,...,NaN,0.30,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Primary,Valleywise Community Health Center- Chandler /,Active,NaN,Reach Out and Read Arizona,NaN,"Southwest Human Development, AZ",NaN,NaN,811 S Hamilton,...,NaN,0.45,NaN,NaN,0.01,NaN,NaN,NaN,NaN,NaN

In [13]:
# Create a Pandas Excel writer using XlsxWriter as the engine.
writer = pd.ExcelWriter('Site_Data_Impact.xlsx', engine='xlsxwriter')

In [14]:
## Filter out for Active Sites
site_data_active_df = site_data_df.loc[(site_data_df['Status'] == 'Active')]
site_data_active_df = site_data_active_df['Affiliate Name'].value_counts().rename_axis('Affiliate').reset_index(name='Active Sites')
site_data_active_df.head()

                           Affiliate  Active Sites
0        Independent / International           582
1  Reach Out and Read North Carolina           376
2        Reach Out and Read Colorado           333
3       Reach Out and Read Minnesota           301
4   Reach Out and Read Massachusetts           264

In [15]:
site_data_active_nonreporting_df = site_data_df.loc[(site_data_df['Status'] == 'Active - Non-Reporting')]
site_data_active_nonreporting_df = site_data_active_nonreporting_df['Affiliate Name'].value_counts().rename_axis('Affiliate').reset_index(name='Active - Non-Reporting Sites')
site_data_active_nonreporting_col = site_data_active_nonreporting_df['Active - Non-Reporting Sites']
site_data_active_df = site_data_active_df.join(site_data_active_nonreporting_col)
site_data_active_df.head()

,Affiliate,Active Sites,Active - Non-Reporting Sites
0,Independent / International,582,30.0
1,Reach Out and Read North Carolina,376,23.0
2,Reach Out and Read Colorado,333,11.0
3,Reach Out and Read Minnesota,301,5.0
4,Reach Out and Read Massachusetts,264,5.0

In [16]:
site_data_CovidFreeze_df = site_data_df.loc[(site_data_df['Status'] == 'COVID-19 Freeze')]
site_data_CovidFreeze_df = site_data_CovidFreeze_df['Affiliate Name'].value_counts().rename_axis('Affiliate').reset_index(name='COVID-19 Freeze Sites')
site_data_CovidFreeze_col = site_data_CovidFreeze_df['COVID-19 Freeze Sites']
site_data_active_df = site_data_active_df.join(site_data_CovidFreeze_col)
site_data_active_df.head()

,Affiliate,Active Sites,Active - Non-Reporting Sites,COVID-19 Freeze Sites
0,Independent / International,582,30.0,6.0
1,Reach Out and Read North Carolina,376,23.0,5.0
2,Reach Out and Read Colorado,333,11.0,4.0
3,Reach Out and Read Minnesota,301,5.0,3.0
4,Reach Out and Read Massachusetts,264,5.0,3.0

In [17]:
site_data_S4D_df = site_data_df.loc[(site_data_df['Status'] == 'Slated for deactivation')]
site_data_S4D_df = site_data_S4D_df['Affiliate Name'].value_counts().rename_axis('Affiliate').reset_index(name='Slated for Deactivation Sites')
site_data_S4D_col = site_data_S4D_df['Slated for Deactivation Sites']
site_data_active_df = site_data_active_df.join(site_data_S4D_col)
site_data_active_df.head()

,Affiliate,Active Sites,Active - Non-Reporting Sites,COVID-19 Freeze Sites,Slated for Deactivation Sites
0,Independent / International,582,30.0,6.0,56.0
1,Reach Out and Read North Carolina,376,23.0,5.0,21.0
2,Reach Out and Read Colorado,333,11.0,4.0,9.0
3,Reach Out and Read Minnesota,301,5.0,3.0,9.0
4,Reach Out and Read Massachusetts,264,5.0,3.0,6.0

In [18]:
site_data_total_active_df = site_data_df['Affiliate Name'].value_counts().rename_axis('Affiliate').reset_index(name='Total High Level Active Sites')
site_data_total_active_col = site_data_total_active_df['Total High Level Active Sites']
site_data_active_df = site_data_active_df.join(site_data_total_active_col)
site_data_active_df.head()

,Affiliate,Active Sites,Active - Non-Reporting Sites,COVID-19 Freeze Sites,Slated for Deactivation Sites,Total High Level Active Sites
0,Independent / International,582,30.0,6.0,56.0,663
1,Reach Out and Read North Carolina,376,23.0,5.0,21.0,380
2,Reach Out and Read Colorado,333,11.0,4.0,9.0,333
3,Reach Out and Read Minnesota,301,5.0,3.0,9.0,302
4,Reach Out and Read Massachusetts,264,5.0,3.0,6.0,266

In [19]:
site_data_primary_df = site_data_df.loc[(site_data_df['Site Type'] == 'Primary')]
site_data_primary_df = site_data_primary_df['Affiliate Name'].value_counts().rename_axis('Affiliate').reset_index(name='Number of Primary Sites')
site_data_primary_df['Number of Primary Sites'] = site_data_primary_df['Number of Primary Sites'] / site_data_total_active_col
site_data_primary_col = site_data_primary_df['Number of Primary Sites']
site_data_active_df = site_data_active_df.join(site_data_primary_col)
site_data_active_df.head()

,Affiliate,Active Sites,Active - Non-Reporting Sites,COVID-19 Freeze Sites,Slated for Deactivation Sites,Total High Level Active Sites,Number of Primary Sites
0,Independent / International,582,30.0,6.0,56.0,663,0.651584
1,Reach Out and Read North Carolina,376,23.0,5.0,21.0,380,0.860526
2,Reach Out and Read Colorado,333,11.0,4.0,9.0,333,0.843844
3,Reach Out and Read Minnesota,301,5.0,3.0,9.0,302,0.781457
4,Reach Out and Read Massachusetts,264,5.0,3.0,6.0,266,0.849624

In [20]:
site_data_satellite_df = site_data_df.loc[(site_data_df['Site Type'] == 'Satellite')]
site_data_satellite_df = site_data_satellite_df['Affiliate Name'].value_counts().rename_axis('Affiliate').reset_index(name='Number of Satellite Sites')
site_data_satellite_df['Number of Satellite Sites'] = site_data_satellite_df['Number of Satellite Sites'] / site_data_total_active_col
site_data_satellite_col = site_data_satellite_df['Number of Satellite Sites']
site_data_active_df = site_data_active_df.join(site_data_satellite_col)
site_data_active_df.head()

,Affiliate,Active Sites,Active - Non-Reporting Sites,COVID-19 Freeze Sites,Slated for Deactivation Sites,Total High Level Active Sites,Number of Primary Sites,Number of Satellite Sites
0,Independent / International,582,30.0,6.0,56.0,663,0.651584,0.348416
1,Reach Out and Read North Carolina,376,23.0,5.0,21.0,380,0.860526,0.357895
2,Reach Out and Read Colorado,333,11.0,4.0,9.0,333,0.843844,0.315315
3,Reach Out and Read Minnesota,301,5.0,3.0,9.0,302,0.781457,0.268212
4,Reach Out and Read Massachusetts,264,5.0,3.0,6.0,266,0.849624,0.293233

In [21]:
site_data_active_df.sort_values(by=['Affiliate'])

,Affiliate,Active Sites,Active - Non-Reporting Sites,COVID-19 Freeze Sites,Slated for Deactivation Sites,Total High Level Active Sites,Number of Primary Sites,Number of Satellite Sites
41,Delaware (TIROS 1),16,NaN,NaN,NaN,16,0.375000,0.125000
40,Idaho (Curiosity Rover),21,NaN,NaN,NaN,22,0.636364,0.136364
0,Independent / International,582,30.0,6.0,56.0,663,0.651584,0.348416
19,Michigan (Mars Pathfinder),114,NaN,NaN,NaN,124,0.677419,0.241935
16,PA (excluding Greater Philadelphia),134,NaN,NaN,NaN,162,0.598765,0.234568
34,Reach Out and Read Alabama,56,NaN,NaN,NaN,57,0.701754,0.122807
13,Reach Out and Read Arizona,168,1.0,1.0,1.0,179,0.715084,0.273743
15,Reach Out and Read Bay Area,139,NaN,NaN,NaN,164,0.597561,0.237805
2,Reach Out and Read Colorado,333,11.0,4.0,9.0,333,0.843844,0.315315
27,Reach Out and Read Connecticut,82,NaN,NaN,NaN,83,0.734940,0.228916
10,Reach Out and Read Florida (excluding Palm Bea...,192,1.0,1.0,3.0,192,0.744792,0.265625
11,Reach Out and Read Georgia,178,1.0,1.0,2.0,186,0.709677,0.268817
7,Reach Out and Read Greater New York,212,2.0,2.0,4.0,228,0.758772,0.254386
26,Reach Out and Read Greater Philadelphia,83,NaN,NaN,NaN,86,0.732558,0.220930
17,Reach Out and Read Illinois,126,NaN,NaN,NaN,129,0.697674,0.279070
18,Reach Out and Read Indiana,119,NaN,NaN,NaN,125,0.688000,0.264000
29,Reach Out and Read Inland Empire (California),70,NaN,NaN,NaN,75,0.760000,0.160000
22,Reach Out and Read Iowa,98,NaN,NaN,NaN,100,0.670000,0.260000
37,Reach Out and Read Kansas City,37,NaN,NaN,NaN,37,0.702703,0.135135
28,Reach Out and Read Kentucky,74,NaN,NaN,NaN,82,0.719512,0.207317
4,Reach Out and Read Massachusetts,264,5.0,3.0,6.0,266,0.849624,0.293233
3,Reach Out and Read Minnesota,301,5.0,3.0,9.0,302,0.781457,0.268212
33,Reach Out and Read National Capital Region,57,NaN,NaN,NaN,60,0.666667,0.133333
32,Reach Out and Read New Hampshire,60,NaN,NaN,NaN,60,0.766667,0.166667
24,Reach Out and Read New Jersey,95,NaN,NaN,NaN,97,0.680412,0.216495
1,Reach Out and Read North Carolina,376,23.0,5.0,21.0,380,0.860526,0.357895
12,Reach Out and Read Ohio,177,1.0,1.0,1.0,183,0.721311,0.267760
23,Reach Out and Read Oklahoma,98,NaN,NaN,NaN,99,0.676768,0.232323
31,Reach Out and Read Orange County (California),64,NaN,NaN,NaN,66,0.727273,0.166667
14,Reach Out and Read Oregon,162,1.0,NaN,1.0,168,0.630952,0.238095
39,Reach Out and Read Palm Beach County (Florida),32,NaN,NaN,NaN,32,0.812500,0.093750
30,Reach Out and Read Rhode Island,66,NaN,NaN,NaN,67,0.761194,0.164179
20,Reach Out and Read San Diego (California),105,NaN,NaN,NaN,108,0.759259,0.259259
8,Reach Out and Read South Carolina,197,1.0,2.0,3.0,201,0.825871,0.268657
35,Reach Out and Read St. Louis (Missouri),52,NaN,NaN,NaN,52,0.673077,0.115385
9,Reach Out and Read Texas,196,1.0,2.0,3.0,196,0.816327,0.270408
21,Reach Out and Read Upstate New York,99,NaN,NaN,NaN,101,0.772277,0.267327
38,Reach Out and Read Vermont,32,NaN,NaN,NaN,37,0.702703,0.135135
6,Reach Out and Read Washington,241,3.0,2.0,5.0,241,0.763485,0.257261
36,Reach Out and Read West Michigan,47,NaN,NaN,NaN,47,0.680851,0.127660
25,Reach Out and Read Western Virginia,93,NaN,NaN,NaN,95,0.663158,0.200000
5,Reach Out and Read Wisconsin,258,4.0,2.0,5.0,259,0.760618,0.262548